apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: lighthouse
  repo: https://ethpandaops.github.io/ethereum-helm-charts
  version: 1.1.5
  releaseName: lighthouse
  namespace: default
  valuesFile: values-override.yaml