apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: reth
  repo: https://ethpandaops.github.io/ethereum-helm-charts
  version: 0.0.15
  releaseName: reth
  namespace: default
  valuesFile: values-override.yaml